### PR TITLE
feat: check that async_early_return is applied on async functions

### PR DESCRIPTION
**Pull request by fgsalomon**

### CODE REVIEW

**Comment by fgsalomon** [comment]
To me this should be handled by custom lint rules but [ruff still doesn't provide a plugin system](https://github.com/astral-sh/ruff/issues/283) like [flake8 does](https://flake8.pycqa.org/en/latest/plugin-development/).

**Comment by acostapazo** [comment]
> To me this should be handled by custom lint rules but https://github.com/astral-sh/ruff/issues/283 like [flake8 does](https://flake8.pycqa.org/en/latest/plugin-development/).

Yes, in the meantime, we can apply solutions similar to what you proposed. We should also implement something similar on`early_return` in async functions.


Should we return a `Failure(AsyncDecorationError())` or maybe we just raise an exception and stop the runtime as we do in https://github.com/alice-biometrics/meiga/blob/main/meiga/result.py#L69

**Comment by acostapazo** [comment]
Otherwise, you have followed the same definition as `UnexpectedDecorationOrderError`, `UnexpectedDecorationOrderError` so probably it is ok 🤔 

```python
         if isinstance(func, staticmethod):
                return Failure(UnexpectedDecorationOrderError())  # type: ignore
            elif isinstance(func, classmethod):
                return Failure(UnexpectedDecorationOrderError())  # type: ignore
            elif not inspect.iscoroutinefunction(func):
                return Failure(AsyncDecorationError())  # type: ignore
```

**Comment by fgsalomon** [comment]
> Otherwise, you have followed the same definition as `UnexpectedDecorationOrderError`, `UnexpectedDecorationOrderError` so probably it is ok 🤔
> 
> ```python
>          if isinstance(func, staticmethod):
>                 return Failure(UnexpectedDecorationOrderError())  # type: ignore
>             elif isinstance(func, classmethod):
>                 return Failure(UnexpectedDecorationOrderError())  # type: ignore
>             elif not inspect.iscoroutinefunction(func):
>                 return Failure(AsyncDecorationError())  # type: ignore
> ```

I was going to throw an exception but I saw that and followed suit.

**Comment by fgsalomon** [comment]
I guess we can use custom code inspections in PyCharm to detect this kind of things:
image

**Comment by fgsalomon** [comment]
> To me this should be handled by custom lint rules but [ruff still doesn't provide a plugin system](https://github.com/astral-sh/ruff/issues/283) like [flake8 does](https://flake8.pycqa.org/en/latest/plugin-development/).

I've just discovered [Fixit](https://fixit.readthedocs.io/en/latest/guide.html). I think it should be easy to write a custom rule with it.

**Pull request merged**
